lib++.install has been updated

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -119,8 +119,9 @@ matrix:
     - os: linux
       dist: focal
       env: >
-           COMPILER=clang++-12 TOOLSET=clang-12 CPPSTD=c++2a
+           COMPILER=clang++-12 TOOLSET=clang CPPSTD=c++2a
            BOOST_VER=1.75.0
+           B2FLAGS="cxxflags=-v linkflags=-v"
       addons:
         apt:
           update: true
@@ -146,7 +147,8 @@ install:
   - |
     if [[ "${CXX%%+*}" == "clang" ]]; then
       bash <( curl -s https://raw.githubusercontent.com/serge-klim/cihelpers/master/travis/lib++.install)
-      export B2FLAGS="cxxflags=-isystem${TRAVIS_BUILD_DIR}/llvm/out/include/c++/v1 linkflags=-L${TRAVIS_BUILD_DIR}/llvm/out/lib"
+      [ $? -ne 0 ] && exit 1
+      export B2FLAGS="${B2FLAGS} cxxflags=-isystem${TRAVIS_BUILD_DIR}/llvm/out/include/c++/v1 linkflags=-L${TRAVIS_BUILD_DIR}/llvm/out/lib"
       export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${TRAVIS_BUILD_DIR}/llvm/out/lib"
     fi
   ############################################################################
@@ -154,7 +156,7 @@ install:
   ############################################################################
   - |
     cd ${TRAVIS_BUILD_DIR}
-    bash <( curl -s https://raw.githubusercontent.com/serge-klim/cihelpers/master/travis/boost.install) toolset=${TOOLSET} cxxflags="-std=${CPPSTD}" ${B2FLAGS} address-model=64 threading=multi --layout=versioned --with-test -d0 stage debug
+    bash <( curl -s https://raw.githubusercontent.com/serge-klim/cihelpers/master/travis/boost.install) toolset=${TOOLSET} cxxflags="-std=${CPPSTD}" ${B2FLAGS} address-model=64 threading=multi --layout=versioned --with-test stage debug
     export BOOST_ROOT=${TRAVIS_BUILD_DIR}/boost_${BOOST_VER//./_}
     cd ${TRAVIS_BUILD_DIR}
   - cat ${BOOST_ROOT}/project-config.jam
@@ -164,7 +166,7 @@ install:
     if [[ "${COVERAGE}" == "ON" ]]; then
       export B2FLAGS="${B2FLAGS} cxxflags=\"--coverage\" linkflags=\"--coverage\""
     fi
-
+  #- cd ${TRAVIS_BUILD_DIR} && curl --retry 5 -s https://raw.githubusercontent.com/serge-klim/cihelpers/master/project-config.jam > project-config.jam
 script:
   - cat project-config.jam
   - ls ${BOOST_ROOT}
