lib++.install has been updated

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,12 +10,12 @@ matrix:
     # - os: osx
     #   osx_image: xcode9.4
     #   env: >
-    #        COMPILER=clang++-5.0 TOOLSET=clang CPPSTD=c++1y
+    #        COMPILER=clang++-5.0 TOOLSET=clang CPPSTD=1y
     #        BOOST_VER=1.66.0
     - os: linux
       dist: trusty
       env: >
-           COMPILER=g++-4.8 TOOLSET=gcc-4.8 CPPSTD=c++11
+           COMPILER=g++-4.8 TOOLSET=gcc-4.8 CPPSTD=11
            BOOST_VER=1.67.0
       addons:
         apt:
@@ -28,7 +28,7 @@ matrix:
     - os: linux
       dist: precise
       env: >
-           COMPILER=g++-4.9 TOOLSET=gcc-4.9 CPPSTD=c++11
+           COMPILER=g++-4.9 TOOLSET=gcc-4.9 CPPSTD=11
            BOOST_VER=1.67.0
       addons:
         apt:
@@ -41,7 +41,7 @@ matrix:
     - os: linux
       dist: precise
       env: >
-           COMPILER=g++-6 TOOLSET=gcc-6 CPPSTD=c++11
+           COMPILER=g++-6 TOOLSET=gcc-6 CPPSTD=11
            BOOST_VER=1.67.0
       addons:
         apt:
@@ -54,7 +54,7 @@ matrix:
     - os: linux
       dist: trusty
       env: >
-           COMPILER=g++-7 TOOLSET=gcc-7 CPPSTD=c++11
+           COMPILER=g++-7 TOOLSET=gcc-7 CPPSTD=11
            BOOST_VER=1.67.0
       addons:
         apt:
@@ -67,7 +67,7 @@ matrix:
     - os: linux
       dist: bionic
       env: >
-           COMPILER=g++-10 TOOLSET=gcc-10 CPPSTD=c++20
+           COMPILER=g++-10 TOOLSET=gcc-10 CPPSTD=latest
            BOOST_VER=1.75.0
       addons:
         apt:
@@ -80,7 +80,7 @@ matrix:
     - os: linux
       dist: precise
       env: >
-           COMPILER=clang++-3.6 TOOLSET=clang CPPSTD=c++1y
+           COMPILER=clang++-3.6 TOOLSET=clang CPPSTD=1y
            BOOST_VER=1.66.0
       addons:
         apt:
@@ -93,8 +93,9 @@ matrix:
     - os: linux
       dist: trusty
       env: >
-           COMPILER=clang++-4.0 TOOLSET=clang CPPSTD=c++1y
+           COMPILER=clang++-4.0 TOOLSET=clang CPPSTD=1y
            BOOST_VER=1.66.0
+           B2FLAGS="cxxflags=-v linkflags=-v"
       addons:
         apt:
           update: true
@@ -106,8 +107,9 @@ matrix:
     - os: linux
       dist: trusty
       env: >
-           COMPILER=clang++-6.0 TOOLSET=clang CPPSTD=c++1y
+           COMPILER=clang++-6.0 TOOLSET=clang CPPSTD=1y
            BOOST_VER=1.67.0
+           B2FLAGS="cxxflags=-v linkflags=-v"
       addons:
         apt:
           update: true
@@ -119,8 +121,9 @@ matrix:
     - os: linux
       dist: focal
       env: >
-           COMPILER=clang++-12 TOOLSET=clang-12 CPPSTD=c++2a
+           COMPILER=clang++-12 TOOLSET=clang-12 CPPSTD=2a
            BOOST_VER=1.75.0
+           B2FLAGS="stdlib=libc++ cxxflags=-v linkflags=-v"
       addons:
         apt:
           update: true
@@ -146,7 +149,8 @@ install:
   - |
     if [[ "${CXX%%+*}" == "clang" ]]; then
       bash <( curl -s https://raw.githubusercontent.com/serge-klim/cihelpers/master/travis/lib++.install)
-      export B2FLAGS="cxxflags=-isystem${TRAVIS_BUILD_DIR}/llvm/out/include/c++/v1 linkflags=-L${TRAVIS_BUILD_DIR}/llvm/out/lib"
+      [ $? -ne 0 ] && exit 1
+      export B2FLAGS="${B2FLAGS} cxxflags=-isystem${TRAVIS_BUILD_DIR}/llvm/out/include/c++/v1 linkflags=-L${TRAVIS_BUILD_DIR}/llvm/out/lib"
       export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${TRAVIS_BUILD_DIR}/llvm/out/lib"
     fi
   ############################################################################
@@ -154,7 +158,7 @@ install:
   ############################################################################
   - |
     cd ${TRAVIS_BUILD_DIR}
-    bash <( curl -s https://raw.githubusercontent.com/serge-klim/cihelpers/master/travis/boost.install) toolset=${TOOLSET} cxxflags="-std=${CPPSTD}" ${B2FLAGS} address-model=64 threading=multi --layout=versioned --with-test -d0 stage debug
+    bash <( curl -s https://raw.githubusercontent.com/serge-klim/cihelpers/master/travis/boost.install) toolset=${TOOLSET} cxxstd=${CPPSTD} ${B2FLAGS} address-model=64 threading=multi --layout=versioned --with-test stage debug
     export BOOST_ROOT=${TRAVIS_BUILD_DIR}/boost_${BOOST_VER//./_}
     cd ${TRAVIS_BUILD_DIR}
   - cat ${BOOST_ROOT}/project-config.jam
@@ -164,11 +168,12 @@ install:
     if [[ "${COVERAGE}" == "ON" ]]; then
       export B2FLAGS="${B2FLAGS} cxxflags=\"--coverage\" linkflags=\"--coverage\""
     fi
-
+  #- cd ${TRAVIS_BUILD_DIR} && curl --retry 5 -s https://raw.githubusercontent.com/serge-klim/cihelpers/master/project-config.jam > project-config.jam
 script:
   - cat project-config.jam
   - ls ${BOOST_ROOT}
   - ls ${BOOST_ROOT}/stage/lib
+  - ${CXX} -v
   - cd ${TRAVIS_BUILD_DIR}/test
-  - ${BOOST_ROOT}/b2 toolset=${TOOLSET} cxxflags="-std=${CPPSTD}" ${B2FLAGS} address-model=64 threading=multi -a --layout=versioned -sBOOST_ROOT=${BOOST_ROOT} -sBOOST_BUILD_PATH=${BOOST_ROOT} -sBOOST_VER=x64-${BOOST_VER%.*} -sBOOST_LIBS=${BOOST_ROOT}/stage/lib debug
+  - ${BOOST_ROOT}/b2 toolset=${TOOLSET} cxxstd=${CPPSTD} ${B2FLAGS} address-model=64 threading=multi -a --layout=versioned -sBOOST_ROOT=${BOOST_ROOT} -sBOOST_BUILD_PATH=${BOOST_ROOT} -sBOOST_VER=x64-${BOOST_VER%.*} -sBOOST_LIBS=${BOOST_ROOT}/stage/lib debug
 
